Demo.PresentationLyer/Models/ErrorViewModel.cs
namespace Demo.PresentationLyer.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo.PresentationLyer/Controllers/DepartmentsController.cs
using BusinessLogicLayer.Repositories;
using DataAcessLayer.Models;
using Microsoft.AspNetCore.Mvc;

namespace Demo.PresentationLyer.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly IDepartmentRepositories _repository;

        public DepartmentsController(IDepartmentRepositories repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var departments = _repository.GetAll();
            return View(departments); 
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Department department)
        {
           if(!ModelState.IsValid) return View(department);
           _repository.Create(department);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int? id)
        {
            if (!id.HasValue) return BadRequest();
            var department = _repository.Get(id.Value);
            if(department is null) return NotFound();
            return View(department);
        }  
        public IActionResult Edit(int? id)
        {
            if (!id.HasValue) return BadRequest();
            var department = _repository.Get(id.Value);
            if(department is null) return NotFound();
            return View(department);
        }

        [HttpPost]
        public IActionResult Edit([FromRoute]int id,Department department)
        {
            if(id != department.Id) return BadRequest();
            if(ModelState.IsValid)
            {
                try
                {
                    _repository.Update(department);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(department);
        }
        public IActionResult Delete(int? id)
        {
            if (!id.HasValue) return BadRequest();
            var department = _repository.Get(id.Value);
            if (department is null) return NotFound();
            return View(department);
        }

        [HttpPost]
        public IActionResult Delete(Department department)
        {
            if (!ModelState.IsValid) return View(department);
            _repository.Remove(department);
            return RedirectToAction(nameof(Index));
        }
    }

}

Demo.PresentationLyer/Controllers/HomeController.cs
using Demo.PresentationLyer.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Demo.PresentationLyer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Demo.PresentationLyer/Views/Departments/Create.cshtml
@model Department
@{
    ViewData["Title"] = "Create";
}

<h1>Create New Department</h1>

<form asp-action="Create">
    <div class="form-group mb-3">
        <label>Code</label>
        <input class="form-control" asp-for="Code" />
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
    <div class="form-group  mb-3">
        <label>Name</label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group  mb-3">
        <label>Date Of Creation</label>
        <input class="form-control" asp-for="MyProperty" />
    </div>

    <div class="mt-3">
        <button type="submit" class="btn btn-success">Save</button>
        <a class="btn btn-danger" asp-action="Index">Cancel</a>
    </div>
</form>

Demo.PresentationLyer/Views/Departments/Delete.cshtml
@model Department
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>


<form asp-action="Delete">
    <div class="form-group mb-3">
        <label>Code</label>
        <input class="form-control" asp-for="Code" />
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
    <div class="form-group  mb-3">
        <label>Name</label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group  mb-3">
        <label>Date Of Creation</label>
        <input class="form-control" asp-for="MyProperty" />
    </div>

    <div class="mt-3">
        <button type="submit" class="btn btn-danger">Delete</button>
        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
    </div>
</form>

Demo.PresentationLyer/Views/Departments/Details.cshtml
@model Department
@{
    ViewData["Title"] = "Details";
}

<h1 class="mb-4">@Model.Name Department Details</h1>

<div class="form-group mb-3">
    <label>Code</label>
    <input readonly class="form-control" asp-for="Code" />
</div>
<div class="form-group  mb-3">
    <label>Name</label>
    <input readonly class="form-control" asp-for="Name" />
</div>
<div class="form-group  mb-3">
    <label>Date Of Creation</label>
    <input readonly class="form-control" asp-for="MyProperty" />
</div>

<div class="mt-3">
    <a class="btn btn-success" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    <a class="btn btn-secondary" asp-action="Index">Back</a>
</div>

Demo.PresentationLyer/Views/Departments/Edit.cshtml
@model Department
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit @Model.Name Dapartment</h1>


<form asp-action="Edit">
    <div class="form-group mb-3">
        <label>Code</label>
        <input class="form-control" asp-for="Code" />
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
    <div class="form-group  mb-3">
        <label>Name</label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group  mb-3">
        <label>Date Of Creation</label>
        <input class="form-control" asp-for="MyProperty" />
    </div>

    <div class="mt-3">
        <button type="submit" class="btn btn-success">Update</button>
        <a class="btn btn-danger" asp-action="Index">Cancel</a>
    </div>
</form>

Demo.PresentationLyer/Views/Departments/Index.cshtml
@model IEnumerable<Department>
@{
    ViewData["Title"] = "Index";
}
<a class="btn btn-primary my-3" asp-action="Create">Create Department</a>
@if (Model.Any())
{
    <h1>
        All Departments
    </h1>

    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <td>@Html.DisplayNameFor(d => d.Code)</td>
                <td>@Html.DisplayNameFor(d => d.Name)</td>
                <td>@Html.DisplayNameFor(d => d.MyProperty)</td>

                <td>Deatails</td>
                <td>Edit</td>
                <td>Delete</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Code</td>
                    <td>@item.Name</td>
                    <td>@item.MyProperty</td>

                    <td><a asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-eye me-2"></i>Detalis</a></td>
                    <td><a asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit me-2"></i>Edit</a></td>
                    <td><a asp-action="Delete" asp-route-id="@item.Id"><i class="fas fa-trash me-2"></i>Delete</a></td>
                    
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div>
       <h1 class="text-center alert-danger">There Is No Departments</h1>
    </div>
}

Demo.PresentationLyer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Demo.PresentationLyer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PresentationLyer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo.PresentationLyer.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PresentationLyer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="index">Departments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo.PresentationLyer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>